language: python
python:
  - "3.4"
  - "3.5"
branches:
  only:
    - master
install:
  - pip install requests
  - pip install pybooru
  - pip install python-telegram-bot
  - pip install retrying
  - pip install schedule
script:
  - python3 animebot.py